FROM node:20

# Add this line to avoid experimental warnings
# Suppress experimental feature warnings
ENV NODE_NO_WARNINGS=1

WORKDIR /app
COPY  package.json .
RUN npm install
COPY . .

CMD ["npm", "run", "dev"]